Features/sql db migration
AlexSpodarev/web-service pull request #5
Opened 2019-01-04 19:30 UTC by AlexSpodarev

Hello @tommybrecher, 
please be kind to review my code of the latest migration to SQLITE3 platform.

Thanks

2019-01-04 20:51 UTC, tommybrecher requested changes
Hi Alex, there are a few changes to be made,

FYI

2019-01-04 20:51 UTC, tommybrecher commented on CHANGELOG.md
> +- URL now can be for example "api/seat" or "api/seat?model=leon&year=2015" - [@AlexSpodarev](https://github.com/AlexSpodarev)
A better description would be:
- Added support for GET requests with query arguments, up to you if to fix or not

2019-01-04 20:51 UTC, tommybrecher commented on REST_API.py
> +    if len(input_params) is not (DB_SIZE - 1):
Like

2019-01-04 20:51 UTC, tommybrecher commented on REST_API.py
> +    The parameters db and db_mode are initialized to database.csv and a (append) respectively,
No more database.csv ..

Also no more params named db and db_mode, please fix.

2019-01-04 20:51 UTC, tommybrecher commented on REST_API.py
> +        param = f' \'{key}\' '
Not clear, please change to 
param = f"'{key}'"

2019-01-04 20:51 UTC, tommybrecher commented on REST_API.py
> +            param += f",'{v}'"
Please add a comment for this whole block, the logic is not straight forward with += and is kinda confusing

2019-01-04 20:51 UTC, tommybrecher commented on REST_API.py
> +        """Closing DB"""
You are not closing the DB,  please remove those comments and add a description of the logic used in this function right under the function declaraton instead

2019-01-05 07:37 UTC, AlexSpodarev commented on CHANGELOG.md
> +- URL now can be for example "api/seat" or "api/seat?model=leon&year=2015" - [@AlexSpodarev](https://github.com/AlexSpodarev)
Totally agree, i've fixed the description.

2019-01-05 08:45 UTC, AlexSpodarev commented
I've fixed the issues and remastered description part throughout the code, 
please review the version @tommybrecher .

2019-01-06 10:29 UTC, tommybrecher approved these changes
LGTM!

2019-01-06 10:31 UTC, merged